### ISSUE TITLE
Unknown/unsupported profile format 21

### ISSUE THREAD

**Issue by landline** [broese/mcbuild#16]
MCBuild 2.0 for Minecraft 1.9.x-1.12.2
Multi-protocol support: 107,109,110,210,315,316,335,338,340
MC Proxy address   :  0.0.0.0:25565
Remote server      :  ###.########.com:25565
Incoming connection from 192.168.###.###:57809
Cannot open file bases.txt for reading: No such file or directory
Cannot open file players.txt for reading: No such file or directory
Selecting protocol 338 (1.12.1) ID=00011201
Unknown/unsupported profile format 21, please report as issue on Github
Failed to parse user profile
EOF on the connection

**Comment by rasulsafa** [comment]
Whenever I try to connect to a server I get this error

**Comment by broese** [comment]
OK, I see Minecraft has changed the format of the user profile again.
Please update and try again. Also please make sure you have logged in at least once using the regular client, so your user profile is properly initialized.

**Comment by broese** [comment]
Fixed with the new profile parsing function
