### ISSUE TITLE
"case 21:" is in the wrong place

### ISSUE THREAD

**Issue by rasulsafa** [broese/mcbuild#18]
On line 833 of mcproxy.c you added `case 21:` to the switch statement. However, you put it before `case 18:` meaning that format 21 gets parsed by the code that's supposed to parse format 18.  `case 21:` should be on line 847 right before `case 20:`. I edited mcproxy.c  and ran the Makefile and it worked.

The new mcproxy.c should be:

        case 18:
            JSON_PARSE(json, "selectedUser", su, json_type_string);
            sprintf(userId, "%s", json_object_get_string(su));

            JSON_PARSE(json, "authenticationDatabase", adb, json_type_object);
            JSON_PARSE(adb, userId, prof, json_type_object);

            JSON_PARSE(prof, "displayName", dn, json_type_string);
            sprintf(userName, "%s", json_object_get_string(dn));

            JSON_PARSE(prof, "accessToken", at, json_type_string);
            sprintf(accessToken, "%s", json_object_get_string(at));

            break;

        case 21: //this is moved from above
        case 20:
            JSON_PARSE(json, "selectedUser", su, json_type_object);
            JSON_PARSE(su, "account", account, json_type_string);
            JSON_PARSE(su, "profile", profile, json_type_string);
            sprintf(userId, "%s", json_object_get_string(profile));

            JSON_PARSE(json, "authenticationDatabase", adb, json_type_object);
            JSON_PARSE(adb, json_object_get_string(account), prof, json_type_object);

            JSON_PARSE(prof, "profiles", profiles, json_type_object);
            JSON_PARSE(profiles, userId, dprof, json_type_object);
            JSON_PARSE(dprof, "displayName", dn, json_type_string);
            sprintf(userName, "%s", json_object_get_string(dn));

            JSON_PARSE(prof, "accessToken", at, json_type_string);
            sprintf(accessToken, "%s", json_object_get_string(at));

            break;

**Comment by broese** [comment]
The reason was, the format of the profile v18 has eventually changed to v20 (there was no v19 to my knowledge), then it changed to v21 that was identical with v18, so both v18 and v21 use the same parser, while v20 uses a slightly different one. Yes, Mojang is THAT retarded.
