### ISSUE TITLE
Handle failure of choose_dot more gracefully

### ISSUE THREAD

**Issue by louwers** [broese/mcbuild#2]
Hi there! I've been using mcbuild and it works beautifully, except for the fact that after 1-15 minutes of building, it always crashes with the following message:

```
mcproxy: mcp_build.c:1087: choose_dot: Assertion `0' failed.
```

Can the event that `choose_dot` fails perhaps be handled more gracefully? For example by trying again or by pausing the build?

**Comment by broese** [comment]
Thank you for reporting it. I agree, many places in the code handle errors ungracefully with a simple assertion and I will try to address that.

However, I would also like to eliminate the source of the issue. Can you supply more information that would help me reproduce it?
- does this assertion occur with a certain type of build, e.g. some specific schematic, or generally?
- prior to that assertion, there should be a message "Fail: i=XXX" printed on stdout (again, not quite graceful :) - what was the number reported?

P.S. I see you originally opened another issue trying to compile it on OSX - did it work out for you?

**Comment by louwers** [comment]
Alright, I'll do some testing!

Nope I've had no luck compiling it on OS X, using Linux now! 😉

**Comment by broese** [comment]
Sorry for the delay, I finally got to fixing bugs.
Please try out the current version - I fixed a really stupid copy-paste bug that calculated the distance to the block incorrectly and ultimately leading to assertion.

**Comment by louwers** [comment]
Amazing, that seems to have fixed it, no more crashes!
