### ISSUE TITLE
MCBuild "Not authenticated with minecraft.net"

### ISSUE THREAD

**Issue by ZafotheNinja** [broese/mcbuild#21]
I made an issue here: 

https://github.com/MultiMC/MultiMC5/issues/2148

Thinking that it was multimc that was causing this error, but they said the problem was with mcbuild.

Basically, I can't join any multiplayer game through mcbuild if I'm using multimc, regular launcher works fine.

Any chance that code can be changed to make these two work together?

**Comment by broese** [comment]
I wrote a parser for MultiMC profile format, I was able to authenticate now.
Please update and try again. However: you must specify the location of your MultiMC accounts.json explicitly using -p option:
```
mcb_start -p /path/to/MultiMC/build/accounts.json server_address
```
You need to check in your Cygwin shell where you can access that file. For example, if you have it at C:\MultiMC\build\accounts.json , try /cygdrive/c/MultiMC/build/accounts.json, or maybe "C:\MultiMC\build\accounts.json" will just work, I'm not sure at the moment.

You can also put it into startup script so save typing. Best, you create a copy of mcb_start, call it mcb_multimc or something and edit the last line like this:
```
./"$APPNAME" -p /cygdrive/c/MultiMC/build/accounts.json "$@"
```

**Comment by ZafotheNinja** [comment]
Awesome, didn't expect it to be patched this fast! 

I'll try it later today and get back with you. 

10/10 Bug Squashing Speed!

**Comment by ZafotheNinja** [comment]
Patch make MCB work as expected! Issue can be closed.
