### ISSUE TITLE
Flip parameter isn't working

### ISSUE THREAD

**Issue by Plastogerm** [broese/mcbuild#23]
This is probably extremely dumb, but I really can't figure it out.

So I was loading my art schematica, placed it and started building, problem is, the schematica was "laying on the ground" which was not what I wanted (I wanted it to stand). So I used "#bu flip 0,1,0" and it did nothing, I used "#bu flip [0|1|0]" and the schematic still didn't change. I've referred to the documentary and still nothing. What's the secret?

**Comment by broese** [comment]
Flip is for mirroring the schematic. Also what is '0,1,0' ? flip takes an optional parameter 'x', 'y' or 'z' denoting the mirroring direction,

What you want is probably "tilt", maybe you will need to repeat it several times to get the right orientation.
**#build tilt**

**Comment by Plastogerm** [comment]
Approved dumb.

OT: Yep, #build tilt works just as I imagined. Thanks alot.
